version: '3.7'
services:
  streamlit:
    build:
      context: streamlit/.
    hostname: streamlit
    restart: always
    container_name: streamlit
    ports:
      - 8501:8501
    links:
      - neo4j
    depends_on:
      - neo4j
    env_file:
      - .env
  neo4j:
    image: neo4j:5.4.0
    restart: always
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/pleaseletmein
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache_size=1G